name: sample_chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.3.0
  flutter: ^3.19.0

dependencies:
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  flutter: { sdk: flutter }
  flutter_hooks: ^0.20.5
  flutter_localizations: { sdk: flutter }
  form_builder_validators: ^9.1.0
  go_router: ^13.2.0
  go_router_builder: ^2.4.1
  hooks_riverpod: ^2.4.10
  ## [intl v0.19.0] is not compatible with [form_builder_validators v9.1.0].
  intl: ^0.18.1
  riverpod_annotation: ^2.3.4

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_test: { sdk: flutter }
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/fonts/
  fonts:
    - family: Marugame-Regular
      fonts:
        - asset: assets/fonts/Marugame-Regular.otf
          weight: 400
    - family: Marugame-Udon
      fonts:
        - asset: assets/fonts/Marugame-Udon.otf
          weight: 400