name: sample_chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.3.0
  flutter: ^3.19.0

dependencies:
  cloud_firestore: ^4.15.7
  flutter: { sdk: flutter }
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_test: { sdk: flutter }
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - .env